### ISSUE TITLE
[FR] support for non circular holes

### ISSUE THREAD

**Issue by TomW1605** [Finn2708/CounterboreBridging#5]
it would be great if this could work on holes that are not all circular. a common example of this would be hexagonal insets for nuts/bolt heads for parts to be assembled

**Comment by Finn2708** [comment]
Hi Thomas, 

this is something I have on my imaginary roadmap, but unfortunately I can't promise a delivery date yet. 
Most likely, this feature will be part of a bigger overhaul with a few other goodies and quality of life updates.

Cheers, 
Finn

**Comment by TomW1605** [comment]
thanks, no rush, its still incredably useful for most things

**Comment by Rarder44** [comment]
hi,
I implemented a working version with non-circular holes and with variable number of cuts.
In the next few days I will do some testing and if it goes well I will make a pr.
(the code is not very clean but it works, unfortunately I can't clean it / comment it better than this due to lack of time)
![image](https://github.com/user-attachments/assets/c1747492-c26c-47eb-9c4a-a43b285ee2d1)

**Comment by Finn2708** [comment]
Hi Luca, 

sorry for the late reply, I was out on vacation.
This looks very interesting. I'm happy to review your PR.

**Comment by Finn2708** [comment]
Thanks for @Rarder44 this is now implemented.
