### ISSUE TITLE
Does not work on Mac

### ISSUE THREAD

**Issue by BenRoe** [Finn2708/CounterboreBridging#8]
I installed the addin and the button is there.
If i click the addin button the window open and i can select the bore face.
After clicking ok, nothing happen.

Fusion 2.0.20460 arm64 [Native] 
macOS 15.0 

![Bildschirmfoto 2024-10-08 um 10 25 32](https://github.com/user-attachments/assets/e43b6749-c3f0-469d-b99b-ced815fec98e)

**Comment by Finn2708** [comment]
Hey, 

this addin is intended to create geometry on counterbore faces that guides your slicer to create straight bridges instead of concentric ones. You are required to provide a face with a circular cutout as the input. This means you'll need to add a hole (or round pocket) to your selected face and run the tool again. 

AFAIK the tool should work on Mac as well, it's just plain old python after all. But I do not own an Apple device to test it on, so please report back if you require further assistance or managed to get it working.

**Comment by BenRoe** [comment]
Hello Finn,
thank you for your response. It was my fault. I selected the wrong face (face inside the hole).
I should select the face with the hole.
